---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: npm
    directory: "/backend-api"
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: "/frontend-ui"
    schedule:
      interval: daily
